# Generated by Django 4.0.8 on 2022-11-13 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipuser',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
